worker_rlimit_nofile 2048;

events {
  worker_connections 1024;
}

http {
  server_tokens off;

  server {
    listen 80;
    server_name localhost;

    # 用 Docker 內建 DNS resolver，動態解析 upstream
    resolver 127.0.0.11 valid=30s;

    location /realms/ {
      set $keycloak http://keycloak:8080;
      proxy_pass          $keycloak;
      proxy_set_header    Host              $host;
      proxy_set_header    X-Real-IP         $remote_addr;
      proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header    X-Forwarded-Proto $scheme;
    }

    location /admin/ {
      set $keycloak http://keycloak:8080;
      proxy_pass          $keycloak;
      proxy_set_header    Host              $host;
      proxy_set_header    X-Real-IP         $remote_addr;
      proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header    X-Forwarded-Proto $scheme;
    }

    location /api/users/ {
      set $user http://user-service:8081;
      proxy_pass          $user;
      proxy_set_header    Host              $host;
      proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    location /api/orders/ {
      set $order http://order-service:8082;
      proxy_pass          $order;
      proxy_set_header    Host              $host;
      proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
    }

    location /api/shipping/ {
      set $shipping http://shipping-service:8083;
      proxy_pass          $shipping;
      proxy_set_header    Host              $host;
      proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
    }
  }
}