apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: momo-system

resources:
  - namespace.yaml
  - secret.yaml
  - gateway/
  - keycloak/
  - services/
  - mysql/
  - kafka/
  - redis/
