spring:
  application:
    name: shipping-service
  datasource:
    url: jdbc:mysql://localhost:3309/shippingdb?useSSL=false&allowPublicKeyRetrieval=true
    username: shipping_svc
    password: shipping_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: shipping-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "com.demo.order.model,com.demo.shipping.model"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/momo-realm
          jwk-set-uri: http://keycloak:8080/realms/momo-realm/protocol/openid-connect/certs

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      service: shipping-service

app:
  kafka:
    topic:
      order-confirmed: order.confirmed
