apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - user-service.yaml
  - order-service.yaml
  - shipping-service.yaml
  - payment-service.yaml
  - inventory-service.yaml
  - box-calculation-service.yaml
