spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://mysql-payment:3310/paymentdb?useSSL=false&allowPublicKeyRetrieval=true
    username: payment_svc
    password: payment_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumer:
    group-id: payment-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      spring.json.trusted.packages: "*"
      spring.json.use.type.headers: false
      spring.json.value.default.type: java.util.Map
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/momo-realm
          jwk-set-uri: http://keycloak:8080/realms/momo-realm/protocol/openid-connect/certs

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces

resilience4j:
  timelimiter:
    instances:
      paymentProcess:
        timeout-duration: 5s
        cancel-running-future: true
 
