# k8s/argocd/keycloak-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: momo-keycloak
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/roseweigee/momo-microservices
    targetRevision: main
    path: k8s/keycloak          # 監聽這個目錄

  destination:
    server: https://kubernetes.default.svc
    namespace: momo-system

  syncPolicy:
    automated:
      prune: true               # Git 刪掉就 K8s 也刪
      selfHeal: true            # 有人手動改 K8s 會自動還原
    syncOptions:
      - CreateNamespace=true    # namespace 不存在自動建立