apiVersion: v1
kind: Secret
metadata:
  name: momo-secret
  namespace: momo-system
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root_pass"
  USER_DB_URL: "jdbc:mysql://mysql-user:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true"
  USER_DB_USER: "user_svc"
  USER_DB_PASS: "user_pass"
