apiVersion: v1
kind: Secret
metadata:
  name: momo-secret
  namespace: momo-system
type: Opaque
stringData:
  USER_DB_URL: "jdbc:mysql://mysql-user:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true"
  USER_DB_USER: "user_svc"
  USER_DB_PASS: "user_pass"
  ORDER_DB_URL: "jdbc:mysql://mysql-order:3306/orderdb?useSSL=false&allowPublicKeyRetrieval=true"
  ORDER_DB_USER: "order_svc"
  ORDER_DB_PASS: "order_pass"
  SHIPPING_DB_URL: "jdbc:mysql://mysql-shipping:3306/shippingdb?useSSL=false&allowPublicKeyRetrieval=true"
  SHIPPING_DB_USER: "shipping_svc"
  SHIPPING_DB_PASS: "shipping_pass"
  MYSQL_ROOT_PASSWORD: "root"
  INVENTORY_DB_URL: "jdbc:mysql://mysql-inventory:3306/inventorydb?useSSL=false&allowPublicKeyRetrieval=true"
  INVENTORY_DB_USER: "inventory_svc"
  INVENTORY_DB_PASS: "inventory_pass"
  PAYMENT_DB_URL: "jdbc:mysql://mysql-payment:3306/paymentdb?useSSL=false&allowPublicKeyRetrieval=true"
  PAYMENT_DB_USER: "payment_svc"
  PAYMENT_DB_PASS: "payment_pass"
